### ISSUE TITLE
Game crashes when reconnecting

### ISSUE THREAD

**Issue by ismael1222** [natanfudge/Crashy#26]
there is a HUGE log of errors, but the main problems are:
[main/FATAL]: Error executing task on Client
java.lang.NullPointerException
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at net.minecraft.scoreboard.Scoreboard.removeTeam(Scoreboard:199)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onTeam(ClientPlayNetworkHandler:2156)
	at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket:122)
	at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket:16)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
--------------------------
and the other problem is:
[ForkJoinPool.commonPool-worker-0/INFO]: [STDOUT]: Removing chunk -55,-82 because it was cached 40 seconds ago, and max age is 5
a lot of these removing chunks+i thinks that is because i reconnect too fast when unloading the world? idk

**Comment by natanfudge** [comment]
What makes you think this is a NEC issue?

**Comment by ismael1222** [comment]
sorry i didnt use the page properly
