### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by ZeezeeWasTaken** [natanfudge/Crashy#36]
Server crashes with this error:
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_13073" because "$$0" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.minecraft.world.dimension.DimensionType.equals(DimensionType:350)
	at net.id.aether.util.RegistryUtil.dimensionMatches(RegistryUtil.java:14)
	at net.minecraft.client.render.BackgroundRenderer.redirect$hak000$adjustVoidVector(BackgroundRenderer:5534)
	at net.minecraft.client.render.BackgroundRenderer.render(BackgroundRenderer:143)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1238)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by natanfudge** [comment]
Not a NEC issue.
