### ISSUE TITLE
my log does not work (crashy)

### ISSUE THREAD

**Issue by epokuser** [natanfudge/Crashy#52]
IT is from minecraft server with plugins

`[12:07:26] [ServerMain/INFO]: Building unoptimized datafixer
[12:07:29] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:07:29] [ServerMain/INFO]: Found new data pack file/iris, loading it automatically
[12:07:33] [ServerMain/INFO]: Loaded 7 recipes
[12:07:36] [Server thread/INFO]: Starting minecraft server version 1.19.2
[12:07:36] [Server thread/INFO]: Loading properties
[12:07:36] [Server thread/INFO]: This server is running petal version git-petal-"eb64b15" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: eb64b15 on ver/1.19.2)
[12:07:37] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:07:37] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:07:37] [Server console handler/ERROR]: [TerminalConsole] Failed to read console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:276) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:282) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180) ~[terminalconsoleappender-1.3.0.jar:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[terminalconsoleappender-1.3.0.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:107) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
	Suppressed: java.io.IOException: The handle is invalid
		at java.io.FileDescriptor.close0(Native Method) ~[?:?]
		at java.io.FileDescriptor.close(FileDescriptor.java:297) ~[?:?]
		at java.io.FileInputStream$1.close(FileInputStream.java:459) ~[?:?]
		at java.io.FileDescriptor.closeAll(FileDescriptor.java:355) ~[?:?]
		at java.io.FileInputStream.close(FileInputStream.java:457) ~[?:?]
		at java.io.BufferedInputStream.close(BufferedInputStream.java:481) ~[?:?]
		at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:366) ~[?:?]
		at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:204) ~[?:?]
		at java.io.InputStreamReader.close(InputStreamReader.java:192) ~[?:?]
		at java.io.BufferedReader.close(BufferedReader.java:525) ~[?:?]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:183) ~[terminalconsoleappender-1.3.0.jar:?]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[terminalconsoleappender-1.3.0.jar:?]
		at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:107) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
[12:07:37] [Server thread/WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[12:07:37] [Server thread/WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[12:07:37] [Server thread/WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[12:07:37] [Server thread/WARN]: [Pufferfish] Debug: Java: 17.0.2, test run: true
[12:07:38] [Server thread/INFO]: Default game type: SURVIVAL
[12:07:38] [Server thread/INFO]: Generating keypair
[12:07:38] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:07:38] [Server thread/INFO]: Using default channel type
[12:07:38] [Server thread/INFO]: Paper: Using Java 11 compression from Velocity.
[12:07:38] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[12:07:41] [Server thread/INFO]: [Iris] Loading 11 libraries... please wait
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\googlecode\concurrentlinkedhashmap\concurrentlinkedhashmap-lru\1.4.2\concurrentlinkedhashmap-lru-1.4.2.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\github\ben-manes\caffeine\caffeine\3.0.5\caffeine-3.0.5.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\org\checkerframework\checker-qual\3.19.0\checker-qual-3.19.0.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\google\errorprone\error_prone_annotations\2.10.0\error_prone_annotations-2.10.0.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\io\timeandspace\smoothie-map\2.0.2\smoothie-map-2.0.2.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\io\timeandspace\jpsg-core\1.4\jpsg-core-1.4.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\org\zeroturnaround\zt-zip\1.14\zt-zip-1.14.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\org\slf4j\slf4j-api\1.6.6\slf4j-api-1.6.6.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\it\unimi\dsi\fastutil\8.5.6\fastutil-8.5.6.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\org\ow2\asm\asm\9.2\asm-9.2.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\rhino\js\1.7R2\js-1.7R2.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\bsf\bsf\2.4.0\bsf-2.4.0.jar
[12:07:41] [Server thread/INFO]: [Iris] Loaded library E:\collabs\ftp\le ftp\the ftp\public files\Server runners\Minecraft\Zell craft\libraries\commons-logging\commons-logging\1.0.4\commons-logging-1.0.4.jar
[12:07:41] [Server thread/ERROR]: Could not load 'plugins\[DL]-RandomEvents-2.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Lib1711]. Please download and install these plugins to run 'RandomEvents'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:293) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:453) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1141) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:07:42] [Server thread/INFO]: [Iris] Loading Iris v2.2.13-1.19.2
[12:07:42] [Server thread/INFO]: [spark] Loading spark v1.9.33
[12:07:42] [Server thread/INFO]: [mcMMO] Loading mcMMO v2.1.218-SNAPSHOT
[12:07:42] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v4.4.2
[12:07:42] [Server thread/INFO]: [ViaVersion] ViaVersion 4.4.2 is now loaded, injecting!
[12:07:42] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[12:07:42] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[12:07:42] [Via-Mappingloader-2/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[12:07:42] [Via-Mappingloader-3/INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[12:07:43] [Via-Mappingloader-4/INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[12:07:43] [Via-Mappingloader-5/INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[12:07:43] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[12:07:43] [Via-Mappingloader-6/INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[12:07:43] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[12:07:43] [Via-Mappingloader-3/INFO]: [ViaVersion] Loading 1.18 -> 1.19 mappings...
[12:07:43] [Server thread/INFO]: [ViaBackwards] Loading ViaBackwards v4.4.2
[12:07:43] [Server thread/INFO]: [ViaBackwards] Loading translations...
[12:07:43] [Via-Mappingloader-2/INFO]: [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
[12:07:43] [Via-Mappingloader-1/INFO]: [ViaBackwards] Loading 1.11 -> 1.10 mappings...
[12:07:43] [Via-Mappingloader-1/INFO]: [ViaBackwards] Loading 1.12 -> 1.11 mappings...
[12:07:43] [Via-Mappingloader-3/INFO]: [ViaBackwards] Loading 1.13.2 -> 1.13 mappings...
[12:07:43] [Via-Mappingloader-3/INFO]: [ViaBackwards] Loading 1.13 -> 1.12 mappings...
[12:07:43] [Via-Mappingloader-0/INFO]: [ViaBackwards] Loading 1.14 -> 1.13.2 mappings...
[12:07:43] [Via-Mappingloader-1/INFO]: [ViaBackwards] Loading 1.15 -> 1.14 mappings...
[12:07:43] [Via-Mappingloader-5/INFO]: [ViaBackwards] Loading 1.16 -> 1.15 mappings...
[12:07:43] [Via-Mappingloader-6/INFO]: [ViaBackwards] Loading 1.16.2 -> 1.16 mappings...
[12:07:44] [Via-Mappingloader-2/INFO]: [ViaBackwards] Loading 1.17 -> 1.16.2 mappings...
[12:07:44] [Via-Mappingloader-4/INFO]: [ViaBackwards] Loading 1.18 -> 1.17 mappings...
[12:07:44] [Via-Mappingloader-0/INFO]: [ViaBackwards] Loading 1.19 -> 1.18 mappings...
[12:07:44] [Server thread/INFO]: [ViaRewind] Loading ViaRewind v2.0.2
[12:07:44] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:07:44] [Server thread/INFO]: [Iris] Enabling Iris v2.2.13-1.19.2
[12:07:44] [Server thread/INFO]: [Iris] [Iris]: Locating NMS Binding for v1_19_R1
[12:07:45] [Server thread/INFO]: [Iris] [Iris]: Craftbukkit v1_19_R1  NMSBinding19_2 Successfully Bound
[12:07:46] [Server thread/INFO]: [ViaRewind] Enabling ViaRewind v2.0.2
[12:07:46] [Server thread/INFO]: Preparing level "world"
[12:07:49] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:07:49] [Server thread/INFO]: Time elapsed: 356 ms
[12:07:49] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[12:07:49] [Server thread/INFO]: Time elapsed: 166 ms
[12:07:49] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[12:07:49] [Server thread/INFO]: Time elapsed: 207 ms
[12:07:49] [Server thread/INFO]: [spark] Enabling spark v1.9.33
[12:07:50] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[12:07:50] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.218-SNAPSHOT
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: config.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: config.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: config.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [Debug] No errors found in config.yml!
[12:07:50] [Server thread/INFO]: [mcMMO] Loading locale from plugins\mcMMO\locales\locale_override.properties
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: advanced.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: advanced.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: advanced.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [Debug] No errors found in advanced.yml!
[12:07:50] [Server thread/INFO]: [mcMMO] Platform String: 1.19.2-R0.1-SNAPSHOT
[12:07:50] [Server thread/INFO]: [mcMMO] Minecraft version determined to be - 1.19.2
[12:07:50] [Server thread/INFO]: [mcMMO] Loading compatibility layers...
[12:07:50] [Server thread/INFO]: [mcMMO] Finished loading compatibility layers.
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: persistent_data.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: persistent_data.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: persistent_data.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [Debug] No errors found in persistent_data.yml!
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: upgrades_overhaul.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: upgrades_overhaul.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: upgrades_overhaul.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: treasures.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: treasures.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: treasures.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: fishing_treasures.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: fishing_treasures.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: fishing_treasures.yml
[12:07:50] [Server thread/INFO]: [mcMMO] Registering enchantments for Fishing Book...
[12:07:50] [Server thread/INFO]: [mcMMO] Loading mcMMO potions.yml File...
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: coreskills.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: coreskills.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: coreskills.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Initializing config: sounds.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: sounds.yml
[12:07:50] [Server thread/INFO]: [mcMMO] [config] Config initialized: sounds.yml
[12:07:50] [Server thread/INFO]: [mcMMO] Loading mcMMO skillranks.yml File...
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Initializing config: child.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: child.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Config initialized: child.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Initializing config: repair.vanilla.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: repair.vanilla.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Config initialized: repair.vanilla.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Initializing config: salvage.vanilla.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: salvage.vanilla.yml
[12:07:54] [Server thread/INFO]: [mcMMO] [config] Config initialized: salvage.vanilla.yml
[12:07:55] [Server thread/INFO]: [mcMMO] (plugins\mcMMO\flatfile\mcmmo.users) Validating database file..
[12:07:55] [Server thread/INFO]: [mcMMO] Enabling Acrobatics Skills
[12:07:55] [Server thread/INFO]: [mcMMO] Registered subskill: Roll
[12:07:55] [Server thread/INFO]: [mcMMO] [config] Initializing config: experience.yml
[12:07:55] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: experience.yml
[12:07:55] [Server thread/INFO]: [mcMMO] [config] Config initialized: experience.yml
[12:07:55] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
[12:07:55] [Server thread/INFO]: [mcMMO] [config] Initializing config: chat.yml
[12:07:55] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: chat.yml
[12:07:55] [Server thread/INFO]: [mcMMO] [config] Config initialized: chat.yml
[12:07:55] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.4.2
[12:07:55] [Server thread/INFO]: [ViaBackwards] Enabling ViaBackwards v4.4.2
[12:07:56] [Server thread/INFO]: Running delayed init tasks
[12:07:56] [Server thread/INFO]: [Iris]: Server type & version: git-petal-"eb64b15" (MC: 1.19.2)
[12:07:56] [Server thread/INFO]: [Iris]: Bukkit version: 1.19.2-R0.1-SNAPSHOT
[12:07:56] [Server thread/INFO]: [Iris]: Java version: 17
[12:07:56] [Server thread/INFO]: [Iris]: Custom Biomes: 87
[12:07:56] [Server thread/INFO]: [Iris]: Custom Dimensions: 1
[12:07:56] [Server thread/INFO]: [Iris]:   overworld v2086
[12:07:56] [Server thread/INFO]: [Iris]: 
[12:07:56] [Server thread/INFO]: 
[12:07:56] [Server thread/INFO]:             @@@@@@@@@@@@@@@@@
[12:07:56] [Server thread/INFO]:          @@&&&&&&&&&&&&&&&   .(((()))).                     
[12:07:56] [Server thread/INFO]:         @@@&&&&&&&&&&&&&  .((((((())))))).                  
[12:07:56] [Server thread/INFO]:         @@@&&&&&&&&&&&&  ((((((((()))))))))                @
[12:07:56] [Server thread/INFO]:         @@@&&&&@@@@@&    ((((((((-)))))))))               @@
[12:07:56] [Server thread/INFO]:         @@@&&            ((((((({ }))))))))            &&@@@     Iris
[12:07:56] [Server thread/INFO]:         @@               ((((((((-)))))))))    &@@@@@&&&&@@@     by Volmit Software
[12:07:56] [Server thread/INFO]:         @                ((((((((()))))))))  &&&&&&&&&&&&@@@     v2.2.13-1.19.2
[12:07:56] [Server thread/INFO]:                           '((((((()))))))'  &&&&&&&&&&&&&@@@
[12:07:56] [Server thread/INFO]:                              '(((())))'   &&&&&&&&&&&&&&&@@
[12:07:56] [Server thread/INFO]:                                        @@@@@@@@@@@@@@@@@
[12:07:56] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.19.1/2 (760)
[12:07:56] [Server thread/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[12:07:56] [Server thread/INFO]: Done (19.948s)! For help, type "help"
[12:07:57] [Craft Scheduler Thread - 4 - Iris/INFO]: [Iris]: Checking Data Packs...
[12:08:02] [Craft Scheduler Thread - 4 - Iris/INFO]: [Iris]: Data Packs Setup!
[12:08:47] [Server thread/INFO]: [Not Secure] [Server] bakaron
[12:08:54] [User Authenticator #1/INFO]: UUID of player in_Minecraft is d9542b8d-3edf-44ab-8fba-17dd57def56f
[12:08:54] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@32129750[id=d9542b8d-3edf-44ab-8fba-17dd57def56f,name=in_Minecraft,properties={textures=[com.mojang.authlib.properties.Property@426a33f0]},legacy=false] (/127.0.0.1:61879): Missing profile public key.
This server requires secure profiles.
[12:08:54] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@32129750[id=d9542b8d-3edf-44ab-8fba-17dd57def56f,name=in_Minecraft,properties={textures=[com.mojang.authlib.properties.Property@426a33f0]},legacy=false] (/127.0.0.1:61879): Missing profile public key.
This server requires secure profiles.
[12:08:54] [Server thread/INFO]: com.mojang.authlib.GameProfile@32129750[id=d9542b8d-3edf-44ab-8fba-17dd57def56f,name=in_Minecraft,properties={textures=[com.mojang.authlib.properties.Property@426a33f0]},legacy=false] (/127.0.0.1:61879) lost connection: Missing profile public key.
This server requires secure profiles.
[12:09:10] [Server thread/INFO]: Stopping server
[12:09:10] [Server thread/INFO]: [ViaRewind] Disabling ViaRewind v2.0.2
[12:09:10] [Server thread/INFO]: [ViaBackwards] Disabling ViaBackwards v4.4.2
[12:09:10] [Server thread/INFO]: [ViaVersion] Disabling ViaVersion v4.4.2
[12:09:10] [Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[12:09:10] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.218-SNAPSHOT
[12:09:10] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[12:09:10] [Server thread/INFO]: [spark] Disabling spark v1.9.33
[12:09:10] [Server thread/INFO]: [Iris] Disabling Iris v2.2.13-1.19.2
[12:09:11] [Server thread/INFO]: [Iris]: Still waiting to shutdown burster...
[12:09:12] [Server thread/INFO]: [Iris]: Still waiting to shutdown burster...
[12:09:13] [Server thread/INFO]: [Iris]: Still waiting to shutdown burster...
[12:09:14] [Server thread/INFO]: [Iris]: Still waiting to shutdown burster...
[12:09:15] [Server thread/INFO]: [Iris]: Still waiting to shutdown burster...
[12:09:16] [Server thread/INFO]: [Iris]: Still waiting to shutdown burster...
[12:09:17] [Server thread/INFO]: [Iris]: Still waiting to shutdown burster...
[12:09:17] [Server thread/INFO]: [Iris]: Forcing Shutdown...
[12:09:17] [Server thread/INFO]: Saving players
[12:09:17] [Server thread/INFO]: Saving worlds
[12:09:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[12:09:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[12:09:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[12:09:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:09:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:09:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:09:22] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:09:23] [Server thread/INFO]: Flushing Chunk IO
[12:09:23] [Server thread/INFO]: Closing Thread Pool
[12:09:23] [Server thread/INFO]: Closing Server
`

**Comment by natanfudge** [comment]
That's not a crash log
