### ISSUE TITLE
FabricLoader Not working

### ISSUE THREAD

**Issue by Thunderpro333** [natanfudge/Crashy#61]
[13:18:11] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.12
[13:18:11] [main/INFO]: Loading 185 mods:
	- aqupdgrizzly 1.16-1.2.2
	- architectury 1.32.66
	- autoconfig1u 3.3.1 via bettermineshafts
	- bettercaves 1.16.5-1.2
	- bettermineshafts 1.16.4-1.0.2
	- biom4st3r_repackaged_expressions 0.1.0 via moenchantments
	- byg 1.3.6
	- bygvanillabiomes 1.0.0
	- cdsam 1.3.2-Fabric-1.16.5
	- cloth-basic-math 0.6.1 via cloth-config2
	- cloth-config2 4.14.64
	- com_electronwill_night-config_core 3.6.2 via byg
	- com_electronwill_night-config_toml 3.6.2 via byg
	- entityculling 1.5.2
	- eymbra 1.0.0
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via fabric
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-keybindings-v0 0.2.2+3cc0f0907d via fabric
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via fabric
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-models-v0 0.3.1+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-indigo 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-rendering-v0 1.1.3+3cc0f0907d via fabric
	- fabric-rendering-v1 1.6.1+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via fabric
	- fabric-screen-api-v1 1.0.1+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-textures-v0 1.0.7+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.14.12
	- fabricshieldlib 1.4.5+1.16
	- fallingleaves 1.6.0+1.16.5
	- farmersdelight 1.16.5-0.0.7
	- ferritecore 2.1.1
	- fiber 0.23.0-2 via patchouli
	- flytre_lib 0.2.11
	- fpsreducer 1.24-mc1.16.5
	- gateofbabylon 1.4.4-1.16.5
	- geckolib3 3.0.107
	- gildedarmor 1.2.5+fabric-1.16.5
	- grass_pass 1.0.0
	- graveltoflint 1.0.0
	- graveyard 1.1
	- horsestonks 1.0.1
	- hplus 2.3.1
	- illuminations 1.5.1
	- immersive_armors 1.5.0+1.16.5
	- indium 1.0.0+mc1.16.5
	- inventoryhud 3.4.1
	- io_github_douira_glsl-transformer 1.0.1 via iris
	- iris 1.4.5
	- jankson 3.0.1+j1.2.0 via libgui
	- java 8
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- konkrete 1.3.3
	- krypton 0.1.2
	- lambdabettergrass 1.0.3+1.16
	- lambdynlights 1.3.4+1.16
	- libgui 3.2.0+1.16.3 via mocolors
	- libraryferret 3.0.0
	- lithium 0.6.6
	- magiccombatwands 1.0.2
	- mcda 1.5.0
	- medievalentity 2.5.0
	- medievalweapons 1.1.3
	- microconfig 1.0.5 via timeinabottle
	- minecraft 1.16.5
	- mo_glass 1.5-MC1.16.5
	- mo_recipes_fabric 1.0.0
	- mobhealthbar 1-16-5-fabric
	- mobsmainmenu 1.0.1
	- mobz 2.4.6
	- mocolors 1.1.2
	- modmenu 1.16.23
	- moenchant_lib 0.1.0 via moenchantments
	- moenchantments 1.15.2
	- more-structures-add-on-for-william-wythers-overhauled-overworld 1.0
	- morecraftingtables 0.1.3-1.16.3
	- mostructures 1.2.0-1.16.5
	- mousetweaks 2.22
	- multi_item_lib 1.3.0 via netherite_plus
	- musketmod 1.2.2
	- naturescompass 1.16.5-2.0.1-fabric
	- netherite_plus 1.4.5-1.16.5
	- neutral_animals 1.0.0
	- notenoughcrashes 4.1.4+1.16.5
	- notenoughcreativity 1.3.2
	- omega-config 1.0.4 via graveyard
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_slf4j_slf4j-api 1.7.12 via iris
	- oro_config 3.0.0 via netherite_plus
	- ostoverhaul 0.1
	- particle_emitter_biom4st3r 0.1.0 via moenchantments
	- particletitlescreen 1.0.1
	- patchouli 1.16.4-53-FABRIC
	- pehkui 3.6.1+1.14.4-1.19.3
	- perfectaccuracy 1.2
	- periodic 0.2.1
	- pirate 1.1.4
	- reach-entity-attributes 1.1.1 via gateofbabylon
	- rhino 1605.1.5-build.75
	- riverredux 0.1.6
	- sextant 0.5
	- skeletonshurtwither 1.0.0
	- slimeorigin 2.1.0
	- sniffer 1.1.1
	- snorkelmod 1.16.5
	- sodium 0.2.0+build.4
	- somnus 0.0.12-1.16.5
	- spark 1.6.0
	- spruceui 2.0.4+1.16 via lambdabettergrass
	- steel 1.1.0+mc.1.16.5
	- taxfreelevels 1.3-1.16.5
	- terra 5.3.3-BETA+5dd00db8
	- terraform-biome-builder-api-v1 1.0.4 via terrestria
	- terraform-config-api-v1 1.0.3 via terrestria
	- terraform-dirt-api-v1 1.1.3 via terrestria
	- terraform-overworld-biome-extensions-api-v1 1.0.3 via terrestria
	- terraform-shapes-api-v1 1.0.3 via terrestria
	- terraform-surfaces-api-v1 1.0.3 via terrestria
	- terraform-tree-api-v1 1.0.4 via terrestria
	- terraform-wood-api-v1 1.0.3 via terrestria
	- terrestria 2.2.0
	- timeinabottle 1.3-mc1.16.4-fabric
	- titlefixer 1.0+1.16.5
	- torohealth 1.16.5-fabric-6
	- valkyrienskies 2.0.0-alpha6
	- vanillaenhanced 1.5.1
	- visualoverhaul 3.2.0
	- vs_eureka 1.0.0-alpha7
	- waila 1.9.22
	- wildworld 2.0.0+1.16.5
	- william-wythers-overhauled-overworld 1.0.1
	- windchimes 1.1.1
	- worldedit 7.2.5+57d5ac9
	- worldeditcui 1.16.5+02
	- xaerominimap 22.17.0
	- xaeroworldmap 1.28.7
	- yungsapi 1.16.5-Fabric-9
[13:18:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/minha/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:18:12] [main/WARN]: Registration of InjectionPoint FD_IINC with com.nhoryzon.mc.farmersdelight.mixin.util.BeforeInc without specifying namespace is deprecated.
[13:18:13] [main/WARN]: Reference map 'grizzlybear-refmap.json' for grizzlybear.mixins.json could not be read. If this is a development environment you can ignore this message
[13:18:13] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 1 override(s) found
[13:18:13] [main/WARN]: Reference map 'rhino-fabric-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[13:18:13] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[13:18:16] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[13:18:18] [main/WARN]: Error loading class: io/github/apace100/origins/power/PowerType (java.lang.ClassNotFoundException: io/github/apace100/origins/power/PowerType)
[13:18:19] [main/WARN]: Error loading class: io/github/apace100/origins/power/PowerType (java.lang.ClassNotFoundException: io/github/apace100/origins/power/PowerType)
[13:18:19] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.Bootstrap.initialize(Bootstrap:42) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:137) ~[fabric-loader-0.14.12-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:155) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:42) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:137) ~[fabric-loader-0.14.12-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:155) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:42) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:137) ~[fabric-loader-0.14.12-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for slimeorigin.mixins.json:MixinBlock from mod slimeorigin during activity: [Transform -> Method onEntityLand(Lnet/minecraft/class_1922;Lnet/minecraft/class_1297;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEVIRTUAL -> io/github/apace100/origins/power/PowerType::isActive:(Lnet/minecraft/class_1297;)Z]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:155) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:42) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:137) ~[fabric-loader-0.14.12-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.github.apace100.origins.power.PowerType
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:155) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:42) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:137) ~[fabric-loader-0.14.12-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: io.github.apace100.origins.power.PowerType
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:155) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:42) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:137) ~[fabric-loader-0.14.12-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 2 more

**Comment by natanfudge** [comment]
This is not a support forum
