### ISSUE TITLE
Error getting tsrg 

### ISSUE THREAD

**Issue by natanfudge** [natanfudge/Crashy#85]
Unexpected error handling '/getTsrg/{mcVersion}.tsrg'
java.lang.NoClassDefFoundError: okhttp3/internal/http2/Http2Connection$writeWindowUpdateLater$1
at okhttp3.internal.http2.Http2Connection.writeWindowUpdateLater$okhttp(Http2Connection.kt:361)
at okhttp3.internal.http2.Http2Connection.updateConnectionFlowControl$okhttp(Http2Connection.kt:192)
at okhttp3.internal.http2.Http2Stream$FramingSource.updateConnectionFlowControl(Http2Stream.kt:438)
at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:419)
at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:182)
at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:242)
at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
at io.github.crashy.mappings.forge.CorsProxyKt.getAtPath(CorsProxy.kt:33)
at io.github.crashy.mappings.forge.TsrgMappingsProvider.get(TsrgMappingsProvider.kt:16)
at io.github.crashy.mappings.forge.TsrgMappingsProvider$get$1.invokeSuspend(TsrgMappingsProvider.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed: java.lang.NoClassDefFoundError: okhttp3/internal/http2/Http2Connection$writeWindowUpdateLater$1
at okhttp3.internal.http2.Http2Connection.writeWindowUpdateLater$okhttp(Http2Connection.kt:361)
at okhttp3.internal.http2.Http2Connection.updateConnectionFlowControl$okhttp(Http2Connection.kt:192)
at okhttp3.internal.http2.Http2Stream$FramingSource.updateConnectionFlowControl(Http2Stream.kt:438)
at okhttp3.internal.http2.Http2Stream$FramingSource.close(Http2Stream.kt:511)
at okio.ForwardingSource.close(ForwardingSource.kt:32)
at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.kt:314)
at okio.RealBufferedSource.close(RealBufferedSource.kt:477)
at okio.RealBufferedSource$inputStream$1.close(RealBufferedSource.kt:170)
at java.base/java.io.PushbackInputStream.close(PushbackInputStream.java:377)
at java.base/java.util.zip.InflaterInputStream.close(InflaterInputStream.java:231)
at java.base/java.util.zip.ZipInputStream.close(ZipInputStream.java:268)
at kotlin.io.CloseableKt.closeFinally(Closeable.kt:59)
at io.github.crashy.mappings.forge.CorsProxyKt.getAtPath(CorsProxy.kt:37)
... 13 more
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.http2.Http2Connection$writeWindowUpdateLater$1
... 26 more
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.http2.Http2Connection$writeWindowUpdateLater$1
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
... 26 more
java.lang.ClassNotFoundException: okhttp3.internal.http2.Http2Connection$writeWindowUpdateLater$1
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at okhttp3.internal.http2.Http2Connection.writeWindowUpdateLater$okhttp(Http2Connection.kt:361)
at okhttp3.internal.http2.Http2Connection.updateConnectionFlowControl$okhttp(Http2Connection.kt:192)
at okhttp3.internal.http2.Http2Stream$FramingSource.updateConnectionFlowControl(Http2Stream.kt:438)
at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:419)
at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:182)
at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:242)
at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
at io.github.crashy.mappings.forge.CorsProxyKt.getAtPath(CorsProxy.kt:33)
at io.github.crashy.mappings.forge.TsrgMappingsProvider.get(TsrgMappingsProvider.kt:16)
at io.github.crashy.mappings.forge.TsrgMappingsProvider$get$1.invokeSuspend(TsrgMappingsProvider.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by natanfudge** [comment]
Error did not repeat itself
